import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

print("Step 1: Ingesting Supply Chain Edge List...")
# In a production environment, this list is generated by tracking MMSIs across multiple port geofences.
# We are using realistic trade volumes for the US Southeast / Caribbean network.
trade_routes = [
    ('Miami', 'Nassau', 850), ('Port Everglades', 'Nassau', 600),
    ('Miami', 'Freeport', 450), ('Port Everglades', 'Freeport', 550),
    ('Jacksonville', 'Port Everglades', 300), ('Savannah', 'Jacksonville', 400),
    ('Charleston', 'Savannah', 350), ('Panama Canal', 'Miami', 1500),
    ('Panama Canal', 'Port Everglades', 1100), ('Panama Canal', 'Savannah', 800),
    ('Rotterdam', 'Miami', 900), ('Rotterdam', 'Charleston', 750),
    ('Houston', 'Miami', 600), ('Houston', 'Port Everglades', 500)
]

# Convert to Pandas DataFrame
edges_df = pd.DataFrame(trade_routes, columns=['Source', 'Target', 'Traffic_Volume'])

print("Step 2: Building the Mathematical Graph...")
# Initialize a NetworkX Graph
G = nx.from_pandas_edgelist(edges_df, source='Source', target='Target', edge_attr='Traffic_Volume')

print("Step 3: Calculating Eigenvector Centrality...")
# This calculates the structural importance of each port. 
# A port is "central" if it is connected to OTHER highly connected ports.
centrality = nx.eigenvector_centrality_numpy(G, weight='Traffic_Volume')

# Add the centrality scores back to the graph nodes
nx.set_node_attributes(G, centrality, 'centrality')

# Sort and print the most critical ports
print("\n--- SUPPLY CHAIN VULNERABILITY RANKING ---")
ranked_ports = sorted(centrality.items(), key=lambda x: x[1], reverse=True)
for rank, (port, score) in enumerate(ranked_ports, 1):
    print(f"{rank}. {port:<15} (Centrality Score: {score:.3f})")

print("\nStep 4: Rendering Network Topology...")
# ==========================================
# VISUALIZATION
# ==========================================
fig, ax = plt.subplots(figsize=(12, 8))
ax.set_facecolor('#00001a')

# We use the Spring Layout algorithm to physically space the nodes based on their connections
pos = nx.spring_layout(G, k=0.8, seed=42)

# Node sizes will scale exponentially based on their Centrality Score
node_sizes = [v * 5000 for v in centrality.values()]
# Edge thicknesses will scale based on Traffic Volume
edge_weights = [G[u][v]['Traffic_Volume'] / 200 for u, v in G.edges()]

# Draw the Edges (Shipping Routes)
nx.draw_networkx_edges(G, pos, width=edge_weights, edge_color='cyan', alpha=0.5, ax=ax)

# Draw the Nodes (Ports)
# We color them using the 'magma' colormap - higher centrality glows brighter
nodes = nx.draw_networkx_nodes(G, pos, node_size=node_sizes, 
                               node_color=list(centrality.values()), 
                               cmap='magma', edgecolors='white', linewidths=2, ax=ax)

# Add Port Names
nx.draw_networkx_labels(G, pos, font_size=11, font_weight='bold', font_color='white', ax=ax)

plt.title('Maritime Supply Chain: Network Topology & Eigenvector Centrality', color='white', fontsize=14)
plt.colorbar(nodes, label='Eigenvector Centrality (Structural Importance)')

# Clean up axes
ax.set_xticks([])
ax.set_yticks([])
for spine in ax.spines.values():
    spine.set_visible(False)

plt.tight_layout()
plt.show()